version: 0.3

phases:
  install:
    runtime-versions:
      nodejs: 18.0.0
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
