export const user = [
  {
    _id: "650e995a3cdeaf66308676b8",
    fName: "Sumit",
    lName: "Mahat",
    email: "mahatsumit5@gmail.com",
  },
  {
    _id: "7c2f8e4c7909b41f32c70a9d",
    fName: "John",
    lName: "Doe",
    email: "johndoe@example.com",
  },
  {
    _id: "9b3b8faa1f00dce2f431dc25",
    fName: "Alice",
    lName: "Smith",
    email: "alicesmith@example.com",
  },
  {
    _id: "4d6c5a31b9c7e1287e8235af",
    fName: "Michael",
    lName: "Johnson",
    email: "michaeljohnson@example.com",
  },
  {
    _id: "1a9e2b41c8f7d5632f0f4e76",
    fName: "Emma",
    lName: "Brown",
    email: "emmabrown@example.com",
  },
  {
    _id: "3f5e7a9b8c1d6b2e9a4d0e1f",
    fName: "Daniel",
    lName: "Wilson",
    email: "danielwilson@example.com",
  },
  {
    _id: "5e7d3c2b1a9b8f3c6e5d4a2f",
    fName: "Sophia",
    lName: "Martinez",
    email: "sophiamartinez@example.com",
  },
  {
    _id: "8c4b6a2d5e3f1c7b9a8d6e5c",
    fName: "James",
    lName: "Taylor",
    email: "jamestaylor@example.com",
  },
  {
    _id: "2f9e7a4b3c5d1e8f9a6b7c8d",
    fName: "Olivia",
    lName: "Anderson",
    email: "oliviaanderson@example.com",
  },
  {
    _id: "4a6b9c2d3e7f8a9b1c2d3e4f",
    fName: "Liam",
    lName: "Wilson",
    email: "liamwilson@example.com",
  },
];

export const users = [
  {
    email: "alice@example.com",
    password: "password@123",
    fName: "Alice",
    lName: "Smith",
    bio: "Lover of books and coffee.",
    profile: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    email: "bob@example.com",
    password: "password@123",
    fName: "Bob",
    lName: "Johnson",
    bio: "Tech enthusiast and gamer.",
    profile: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    email: "carol@example.com",
    password: "password@123",
    fName: "Carol",
    lName: "Williams",
    bio: "Traveler and food lover.",
    profile: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    email: "dave@example.com",
    password: "password@123",
    fName: "Dave",
    lName: "Brown",
    bio: "Fitness enthusiast and photographer.",
    profile: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    email: "eve@example.com",
    password: "password@123",
    fName: "Eve",
    lName: "Davis",
    bio: "Music lover and artist.",
    profile: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    email: "frank@example.com",
    password: "password@123",
    fName: "Frank",
    lName: "Miller",
    bio: "Gamer and movie buff.",
    profile: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    email: "grace@example.com",
    password: "password@123",
    fName: "Grace",
    lName: "Wilson",
    bio: "Nature lover and writer.",
    profile: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    email: "henry@example.com",
    password: "password@123",
    fName: "Henry",
    lName: "Moore",
    bio: "History buff and chef.",
    profile: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    email: "isla@example.com",
    password: "password@123",
    fName: "Isla",
    lName: "Taylor",
    bio: "Fashionista and traveler.",
    profile: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
